name: Build Signed Release APK
on:
  push:
    branches: [ master ]
  workflow_dispatch: # 网页手动触发打包

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 把base64字符串还原成jks签名文件
      - name: Decode keystore from secret
        run: echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > release.jks

      # 编译带签名Release APK
      - name: Build Signed Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/release.jks -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # 上传打包产物，打包完成可以下载
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: maidong-ktv-release-apk
          path: app/build/outputs/apk/release/ylktv-release.apk
